### ISSUE TITLE
Doesn't seem to work on desktop with Outlet theme

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/storefront-homepage-contact-section#2]
in ticket: #426088-zd-woothemes it is reported that the contact section does not appear when using the Outlet theme. I have replicated this on my local testing environment. 

If I live preview in Storefront, it works as expected:
![see screen shot](http://cld.wthms.co/19iNR/5qQoqV4r+)
http://cld.wthms.co/19iNR/5qQoqV4r

The contact section does show up on mobile (as reported by the user)
@tiagonoronha

**Comment by tiagonoronha** [comment]
Fixed in Outlet.
