### ISSUE TITLE
Contact form goes to email specified in Your Profile, not General Settings

### ISSUE THREAD

**Issue by zandyring** [woocommerce/storefront-homepage-contact-section#5]
The problem is that when the contact section is set up, the email will automatically go to the email address specified in Users > Your Profile for whoever set up the contact section or page. It should use the email address in General > Settings instead.

After a chat with @WPprodigy today, he suspects that there's an issue around the `else` found here: https://github.com/Automattic/jetpack/blob/04fbdf4430dce0c6c41ad390b6fbaaf3b3911ba8/modules/contact-form/grunion-contact-form.php#L1342

See:
https://github.com/Automattic/jetpack/blob/04fbdf4430dce0c6c41ad390b6fbaaf3b3911ba8/modules/contact-form/grunion-contact-form.php#L1342

And
https://github.com/woocommerce/storefront-homepage-contact-section/blob/4d6ae701e36e9c769ccb8e9efeb210e720df10da/storefront-homepage-contact-section.php#L440

**Comment by WPprodigy** [comment]
Re-opening, as I'm pretty sure this isn't fixed per a live chat that came in.

**Comment by tiagonoronha** [comment]
@WPprodigy I've tested it again and it seems to be working as expected, email was delivered to the configured admin address.

Please provide more information.

Closing for now.

**Comment by WPprodigy** [comment]
Looks like something different is being done now and no shortcode use so could be all good, but previously I think it was still broke per these notes: https://github.com/woocommerce/storefront-homepage-contact-section/pull/6#issuecomment-380181900
